# Generated by Django 2.2.5 on 2020-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_detail',
            fields=[
                ('company_username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_realname', models.CharField(max_length=50)),
                ('company_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'company_detail',
            },
        ),
    ]
