# Generated by Django 2.2.5 on 2020-02-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_auto_20200125_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.CharField(max_length=20)),
                ('admin_username', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=20)),
                ('admin_realname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_detail',
            },
        ),
        migrations.CreateModel(
            name='worker_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.CharField(max_length=20)),
                ('worker_username', models.CharField(max_length=20)),
                ('worker_password', models.CharField(max_length=20)),
                ('worker_realname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'worker_detail',
            },
        ),
    ]
