# Generated by Django 2.2.5 on 2020-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0004_admin_detail_worker_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.CharField(max_length=20)),
                ('product_username', models.CharField(max_length=20)),
                ('product_realname', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_detail',
            },
        ),
    ]
