# Generated by Django 2.2.5 on 2020-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0005_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.CharField(max_length=20)),
                ('product_username', models.CharField(max_length=20)),
                ('attribute_id', models.SmallIntegerField()),
                ('attribute_name', models.CharField(max_length=40)),
                ('attribute_required_quantity', models.PositiveIntegerField()),
                ('attribute_current_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
