# Generated by Django 2.2.5 on 2020-02-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0006_attribute_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute_product',
            table='attribute_product',
        ),
    ]
