# Generated by Django 2.2.5 on 2020-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0007_auto_20200212_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_sales_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.CharField(max_length=20)),
                ('product_username', models.CharField(max_length=20)),
                ('month', models.SmallIntegerField()),
                ('year', models.CharField(max_length=4)),
                ('unit_sold', models.PositiveIntegerField()),
                ('unit_produced', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'history_sales_data',
            },
        ),
    ]
