# Generated by Django 2.2.5 on 2020-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0009_all_jobs_job_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.CharField(max_length=20)),
                ('product_username', models.CharField(max_length=20)),
                ('job_id', models.CharField(max_length=20)),
                ('worker_username', models.CharField(max_length=20)),
                ('e_start_time', models.DateTimeField()),
                ('e_end_time', models.DateTimeField()),
                ('a_start_time', models.DateTimeField()),
                ('a_end_time', models.DateTimeField()),
                ('number_jobs', models.SmallIntegerField()),
                ('numer_jobs_done', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'job_assign',
            },
        ),
    ]
