# Generated by Django 2.2.5 on 2020-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0010_job_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_assign',
            name='instruction',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
