# Generated by Django 2.2.5 on 2020-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0011_job_assign_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.CharField(max_length=20)),
                ('worker_username', models.CharField(max_length=20)),
                ('jobs_done', models.PositiveIntegerField()),
                ('jobs_assigned', models.PositiveIntegerField()),
                ('efficiency', models.FloatField()),
                ('tasks_done', models.PositiveIntegerField()),
                ('tasks_assigned', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'worker_data',
            },
        ),
    ]
