# Generated by Django 2.2.5 on 2020-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0014_worker_data_worker_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_data',
            name='worker_password',
        ),
        migrations.AddField(
            model_name='worker_data',
            name='worker_realname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
